version: "3"

services:
  selenium:
    image: selenium/standalone-chrome:3.141.59
    container_name: selenium_server_works
    ports:
      - "4444:4444"
    logging:
      driver: none

  test_runner:
    build:
      context: /Users/<USER_NAME>/LearnQA_Docker/Autotests
      dockerfile: /Users/<USER_NAME>/LearnQA_Docker/compose_2/Dockerfile
    image: tests_run
    container_name: tests_works
    network_mode: "host"
